version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_IP_API_URL=https://ipapi.co/json/
      - VITE_OPEN_WEATHER_API_KEY=<<open weather api key>>
      - VITE_OPEN_WEATHER_API_URL=https://api.openweathermap.org/data/2.5/
      - VITE_OPEN_WEATHER_ICON_URL=https://openweathermap.org/img/wn/
      - VITE_NEWS_API_URL=https://newsapi.org/v2/
      - VITE_NEWS_API_KEY=<<news api key>>
      - VITE_GOOGLE_CLIENT_ID=<<Google auth client id>>
      - VITE_GOOGLE_CLIENT_SECRET= <<Google Client secret>>
